openapi: '3.0.2'
info:
  title: NodeJS Base Project
  version: '1.0'
paths:
  /health:
    get:
      summary: Check server status
      responses:
        '200':
          description: Server Up!
          content:
            application/json:
              schema:
                type: object
                properties:
                  uptime:
                    type: number
                  message:
                    type: string
                  date:
                    type: integer
  /balances:
    get:
      summary: Get balance
      responses:
        '200':
          description: Get balance!
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: number
